const  palavrasComDicas = [
    // --- Nível Fácil ---
    { palavra: "CASA", dica: "Lugar onde se mora", nivel: "fácil" },
    { palavra: "BOLA", dica: "Objeto redondo usado em esportes", nivel: "fácil" },
    { palavra: "GATO", dica: "Animal de estimação que mia", nivel: "fácil" },
    { palavra: "SOL", dica: "Estrela no centro do nosso sistema", nivel: "fácil" },
    { palavra: "ARROZ", dica: "Grão branco, base da culinária brasileira", nivel: "fácil" },
    { palavra: "LIVRO", dica: "Conjunto de folhas com texto", nivel: "fácil" },
    { palavra: "CAFE", dica: "Bebida escura e quente que acorda", nivel: "fácil" },
    { palavra: "MESA", dica: "Móvel com quatro pernas para refeições", nivel: "fácil" },
    { palavra: "PRAIA", dica: "Lugar com areia e mar", nivel: "fácil" },
    { palavra: "FILME", dica: "História contada com imagens em movimento", nivel: "fácil" },
    { palavra: "AGUA", dica: "Líquido incolor essencial para a vida", nivel: "fácil" },
    { palavra: "MUSICA", dica: "Arte de combinar sons e ritmos", nivel: "fácil" },
    { palavra: "AMOR", dica: "Sentimento de grande afeição", nivel: "fácil" },
    { palavra: "JANELA", dica: "Abertura na parede para luz e ventilação", nivel: "fácil" },
    { palavra: "VERDE", dica: "Cor da grama e das folhas", nivel: "fácil" },

    // --- Nível Médio ---
    { palavra: "COMPUTADOR", dica: "Máquina que processa dados", nivel: "médio" },
    { palavra: "VIAGEM", dica: "Deslocamento para um lugar distante", nivel: "médio" },
    { palavra: "CHOCOLATE", dica: "Doce feito a partir do cacau", nivel: "médio" },
    { palavra: "FUTEBOL", dica: "Esporte jogado com os pés e uma bola", nivel: "médio" },
    { palavra: "BIBLIOTECA", dica: "Lugar onde se guardam e emprestam livros", nivel: "médio" },
    { palavra: "ASTRONOMIA", dica: "Ciência que estuda os astros", nivel: "médio" },
    { palavra: "FOTOGRAFIA", dica: "Técnica de criar imagens pela luz", nivel: "médio" },
    { palavra: "DINOSSAURO", dica: "Réptil pré-histórico gigante", nivel: "médio" },
    { palavra: "RECICLAGEM", dica: "Processo de reaproveitamento de materiais", nivel: "médio" },
    { palavra: "ELEFANTE", dica: "Maior mamífero terrestre, com tromba", nivel: "médio" },
    { palavra: "INTERNET", dica: "Rede mundial de computadores", nivel: "médio" },
    { palavra: "CARNAVAL", dica: "Festa popular brasileira com desfiles e samba", nivel: "médio" },
    { palavra: "ALGORITMO", dica: "Sequência de passos para realizar uma tarefa", nivel: "médio" },
    { palavra: "AMARELO", dica: "Cor do sol e da banana madura", nivel: "médio" },
    { palavra: "ORQUESTRA", dica: "Grande grupo de músicos com diversos instrumentos", nivel: "médio" },
    { palavra: "PRESIDENTE", dica: "Chefe de estado de uma república", nivel: "médio" },
    { palavra: "SAUDADE", dica: "Sentimento nostálgico pela falta de algo ou alguém", nivel: "médio" },
    { palavra: "BRASILIA", dica: "Capital do Brasil", nivel: "médio" },
    { palavra: "TECLADO", dica: "Periférico para digitar no computador", nivel: "médio" },
    { palavra: "ARQUITETURA", dica: "Arte e técnica de projetar edificações", nivel: "médio" },

    // --- Nível Difícil ---
    { palavra: "PROTAGONISTA", dica: "Personagem principal de uma história", nivel: "difícil" },
    { palavra: "METAMORFOSE", dica: "Transformação de um ser em outro", nivel: "difícil" },
    { palavra: "PARALELEPIPEDO", dica: "Forma geométrica de seis faces", nivel: "difícil" },
    { palavra: "ORNITORRINCO", dica: "Mamífero australiano que bota ovos e tem bico de pato", nivel: "difícil" },
    { palavra: "FENOMENOLOGIA", dica: "Corrente filosófica que estuda a essência das coisas", nivel: "difícil" },
    { palavra: "OTORRINOLARINGOLOGISTA", dica: "Médico especialista em ouvido, nariz e garganta", nivel: "difícil" },
    { palavra: "QUINTESSENCIA", dica: "A parte mais pura ou essencial de algo", nivel: "difícil" },
    { palavra: "FOTOSSINTESE", dica: "Processo das plantas para produzir seu alimento com luz solar", nivel: "difícil" },
    { palavra: "ONOMATOPEIA", dica: "Palavra que imita o som de algo", nivel: "difícil" },
    { palavra: "CRIPTOGRAFIA", dica: "Técnica de codificar uma mensagem para protegê-la", nivel: "difícil" },
    { palavra: "INFRAESTRUTURA", dica: "Conjunto de serviços básicos para o funcionamento de uma cidade ou país", nivel: "difícil" },
    { palavra: "PROCASTINACAO", dica: "O ato de adiar tarefas importantes", nivel: "difícil" },
    { palavra: "UBIQUIDADE", dica: "A capacidade de estar em todos os lugares ao mesmo tempo", nivel: "difícil" },
    { palavra: "MNEMONICO", dica: "Técnica para auxiliar a memorização", nivel: "difícil" },
    { palavra: "EXCEPCIONALIDADE", dica: "Qualidade do que é fora do comum, excepcional", nivel: "difícil" }
];